use std::{env, fs, path::PathBuf};

fn main() {
    let grammar_path = PathBuf::from("syntax/masm.ungram");
    println!("cargo::rerun-if-changed={}", grammar_path.display());

    let grammar = fs::read_to_string(&grammar_path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", grammar_path.display()));
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is not set"));
    let generated = out_dir.join("generated.rs");

    let generated_source = format!(
        "// @generated by build.rs\n\
         // The ungrammar source is checked in while parser codegen is still being bootstrapped.\n\
         pub const UNGRAMMAR_SOURCE: &str = {grammar:?};\n"
    );
    fs::write(&generated, generated_source)
        .unwrap_or_else(|err| panic!("failed to write {}: {err}", generated.display()));
}
